name: YouTube Plus ++

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "The direct URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      ytplus_url:
        description: "The direct URL to the YouTube Plus (YTLite) .deb file from Filebin"
        default: ""
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YouTube Plus with Tweaks
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Install System Dependencies (make)
        run: |
          brew install make
          brew install ldid

      - name: Set up GNUBin Path
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Cache Theos Directory
        id: theos
        uses: actions/cache@v4.0.1
        env:
          cache-name: theos_cache
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Set up Theos from Repository (if no cache)
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/theos
          ref: 3da31488281ecf4394d10302d2629607f4a1aa07
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Download and Set Up iOS SDK (iPhoneOS13.7)
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS13.7.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Install Cyan (Pyzule-RW Fork)
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Download YouTube IPA
        id: download_youtube
        run: wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/youtube.ipa

      - name: Download YouTube Plus .deb
        id: download_ytp
        run: |
          wget "${{ inputs.ytplus_url }}" --no-verbose -O ${{ github.workspace }}/ytplus.deb

      - name: Clone Safari Extension (Open in YouTube)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/CokePokes/YoutubeExtensions/
          cd YoutubeExtensions
          git sparse-checkout set --no-cone OpenYoutubeSafariExtension.appex
          git checkout
          mv *.appex ${{ github.workspace }}

      - name: Clone YouTubeHeader
        run: |
          THEOS_INCLUDE="$THEOS/include"
          cd "$THEOS_INCLUDE"
          
          if [ ! -d "YouTubeHeader" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
            echo "Cloned YouTubeHeader."
          else
            echo "YouTubeHeader already exists."
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Create YTHeaders Symlink
        run: |
          THEOS_INCLUDE="$THEOS/include"
          cd "$THEOS_INCLUDE"
          
          if [ ! -e "YTHeaders" ]; then
            ln -s YouTubeHeader YTHeaders
            echo "Created symlink YTHeaders -> YouTubeHeader."
          else
            echo "YTHeaders symlink already exists."
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone YouPiP Repository
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git

      - name: Clone YTUHD Repository
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTUHD.git

      - name: Clone Return-YouTube-Dislikes Repository
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git

      - name: Clone DontEatMyContent Repository
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/therealFoxster/DontEatMyContent.git

      - name: Clone YTABGoodies Repository
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTABGoodies.git

      - name: Clone YTABConfig Repository
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git

      - name: Build YouPiP
        run: |
          cd ${{ github.workspace }}/YouPiP
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/youpip.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTUHD
        run: |
          cd ${{ github.workspace }}/YTUHD
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/ytuhd.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Return-YouTube-Dislikes
        run: |
          cd ${{ github.workspace }}/Return-YouTube-Dislikes
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/ryd.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build DontEatMyContent
        run: |
          cd ${{ github.workspace }}/DontEatMyContent
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/donteatmycontent.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTABConfig
        run: |
          cd ${{ github.workspace }}/YTABConfig
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/ytabconfig.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build YTABGoodies
        run: |
          cd ${{ github.workspace }}/YTABGoodies
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/ytabgoodies.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Inject Tweaks into IPA using Cyan
        run: |
          cyan -i ${{ github.workspace }}/youtube.ipa \
          -o ${{ github.workspace }}/YouTubePlus_${{ inputs.tweak_version }}_Tweaks.ipa \
          -f \
          ${{ github.workspace }}/ytplus.deb \
          ${{ github.workspace }}/OpenYoutubeSafariExtension.appex \
          ${{ github.workspace }}/youpip.deb \
          ${{ github.workspace }}/ytuhd.deb \
          ${{ github.workspace }}/ryd.deb \
          ${{ github.workspace }}/donteatmycontent.deb \
          ${{ github.workspace }}/ytabconfig.deb \
          ${{ github.workspace }}/ytabgoodies.deb

      - name: Upload to GitHub Releases (YouTubePlus IPA)
        uses: softprops/action-gh-release@v2.0.1
        with:
          tag_name: v${{ github.run_number }}
          name: YouTubePlus v${{ inputs.tweak_version }} + Tweaks (${{ github.run_number }})
          files: YouTubePlus_${{ inputs.tweak_version }}_Tweaks.ipa
          draft: true